#!/bin/bash
## Description: Run installation sequences in the web container: composer install, drush site:install
## Usage: install
## Example: "ddev install"

echo "Installing composer dependencies (with development dependencies)."
composer install --no-interaction --no-progress --apcu-autoloader || exit 1;
echo "Composer packages are installed"

echo "Running site installation."
drush -y si standard || exit 1;
drush -y en $PROJECTNAME address auto_entitylabel ckeditor field_group focal_point inline_entity_form jsonapi_extras metatag next paragraphs rdf scheduler simple_sitemap upgrade_status || exit 1;
echo "Site installation is finished"

drush uli
